In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Step2- Import Dataset

In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_7f59f753368e4c7289bb479464a5b7cd = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='1vGvKInRR-sR_JaJjxaNFVpn0LXqvnHf-HRgmqCFGgBs',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_7f59f753368e4c7289bb479464a5b7cd.get_object(Bucket='srinivaspavan1-donotdelete-pr-y2lsngdbzsknu1',Key='winequality-red.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()



fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [5]:
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [6]:
dataset.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

Step3- Split Independent and Dpendent Variables

In [7]:
x= dataset.iloc[:,:11]

In [8]:
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [9]:
type(x)

pandas.core.frame.DataFrame

In [10]:
x= dataset.iloc[:,:11].values #convert from dataframe to numpy array

In [11]:
x

array([[  7.4  ,   0.7  ,   0.   , ...,   3.51 ,   0.56 ,   9.4  ],
       [  7.8  ,   0.88 ,   0.   , ...,   3.2  ,   0.68 ,   9.8  ],
       [  7.8  ,   0.76 ,   0.04 , ...,   3.26 ,   0.65 ,   9.8  ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   3.42 ,   0.75 ,  11.   ],
       [  5.9  ,   0.645,   0.12 , ...,   3.57 ,   0.71 ,  10.2  ],
       [  6.   ,   0.31 ,   0.47 , ...,   3.39 ,   0.66 ,  11.   ]])

In [12]:
x.ndim #mandatory to be in 2 dimesion for Linear Regression

2

In [13]:
type(x)

numpy.ndarray

In [14]:
y= dataset.iloc[:,11:]

In [15]:
y.shape

(1599, 1)

In [16]:
y= dataset.iloc[:,11:].values

In [17]:
y

array([[5],
       [5],
       [5],
       ..., 
       [6],
       [5],
       [6]])

Step5-Encode categorical Text Variables

In [18]:
x

array([[  7.4  ,   0.7  ,   0.   , ...,   3.51 ,   0.56 ,   9.4  ],
       [  7.8  ,   0.88 ,   0.   , ...,   3.2  ,   0.68 ,   9.8  ],
       [  7.8  ,   0.76 ,   0.04 , ...,   3.26 ,   0.65 ,   9.8  ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   3.42 ,   0.75 ,  11.   ],
       [  5.9  ,   0.645,   0.12 , ...,   3.57 ,   0.71 ,  10.2  ],
       [  6.   ,   0.31 ,   0.47 , ...,   3.39 ,   0.66 ,  11.   ]])

In [19]:
from sklearn.model_selection import train_test_split                #previously cros_validation was used in sklearn
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
x_test

array([[ 10.8  ,   0.47 ,   0.43 , ...,   3.17 ,   0.76 ,  10.8  ],
       [  8.1  ,   0.82 ,   0.   , ...,   3.36 ,   0.53 ,   9.6  ],
       [  9.1  ,   0.29 ,   0.33 , ...,   3.26 ,   0.84 ,  11.7  ],
       ..., 
       [  9.1  ,   0.34 ,   0.42 , ...,   3.18 ,   0.55 ,  11.4  ],
       [  9.1  ,   0.765,   0.04 , ...,   3.29 ,   0.54 ,   9.7  ],
       [  8.2  ,   0.32 ,   0.42 , ...,   3.27 ,   0.55 ,  12.3  ]])

In [21]:
import keras #Building neural network model back end it has tensorflow
from keras.models import Sequential # initializing model
from keras.layers import Dense # used for adding the neural network layers

Using TensorFlow backend.


In [22]:
model=Sequential()#instance

In [23]:
model.add(Dense(input_dim=11,init="random_uniform",activation="relu",output_dim=6)) #input_dim=no of neurons to have in the input layer(no of independent variables),init=adding weights,activation function,output_dim=next hidden layer
#best thing for output_dim is input_dim/2

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, kernel_initializer="random_uniform", activation="relu", input_dim=11)`
  if __name__ == '__main__':


In [24]:
model.add(Dense(output_dim=6,init="random_uniform",activation="relu"))# adding hidden layer similary like adding weights

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="random_uniform")`
  if __name__ == '__main__':


In [25]:
model.add(Dense(output_dim=1,init="random_uniform"))#adding output layer

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  if __name__ == '__main__':


# In compilation we will define loss strategy(mean square error), weights optimsation startegy(batch grad descent,stocastic grad descent),model performance strategy

In [26]:
model.compile(optimizer='adam',loss='mse',metrics=['mse'])#adam=batch gradent descent

In [27]:
model.fit(x_train,y_train,epochs=1000,batch_size=10)#epochs no of iteration 

Epoch 1/1000
1279/1279 [==============================] - 0s 363us/step - loss: 20.6526 - mean_squared_error: 20.6526
Epoch 2/1000
1279/1279 [==============================] - 0s 321us/step - loss: 4.3573 - mean_squared_error: 4.3573
Epoch 3/1000
1279/1279 [==============================] - 0s 312us/step - loss: 2.0189 - mean_squared_error: 2.0189
Epoch 4/1000
1279/1279 [==============================] - 0s 315us/step - loss: 0.8306 - mean_squared_error: 0.8306
Epoch 5/1000
1279/1279 [==============================] - 0s 311us/step - loss: 0.6363 - mean_squared_error: 0.6363
Epoch 6/1000
1279/1279 [==============================] - 0s 313us/step - loss: 0.6171 - mean_squared_error: 0.6171
Epoch 7/1000
1279/1279 [==============================] - 0s 369us/step - loss: 0.5994 - mean_squared_error: 0.5994
Epoch 8/1000
1279/1279 [==============================] - 0s 317us/step - loss: 0.5894 - mean_squared_error: 0.5894
Epoch 9/1000
1279/1279 [==============================] - 0s 319us/ste

In [28]:
y_pred1=model.predict(x_test)

In [29]:
y_pred1

array([[ 5.82748938],
       [ 5.12794781],
       [ 6.71523952],
       [ 5.46583366],
       [ 6.08452511],
       [ 4.91532755],
       [ 5.43489218],
       [ 6.17238903],
       [ 4.91706753],
       [ 4.87283707],
       [ 5.38543653],
       [ 5.51644135],
       [ 5.85878372],
       [ 5.04291391],
       [ 5.62631798],
       [ 6.39804697],
       [ 6.95915937],
       [ 5.85571146],
       [ 6.1012373 ],
       [ 5.10078573],
       [ 6.45224571],
       [ 5.28215981],
       [ 5.74686813],
       [ 6.2046442 ],
       [ 5.63309813],
       [ 4.98946381],
       [ 5.12429619],
       [ 6.59672022],
       [ 5.14955902],
       [ 6.48760509],
       [ 6.14617109],
       [ 5.89855862],
       [ 5.69151592],
       [ 5.42579746],
       [ 5.83588123],
       [ 6.36798096],
       [ 5.17228746],
       [ 5.69742107],
       [ 6.55268574],
       [ 5.93992996],
       [ 5.48255157],
       [ 6.11818933],
       [ 6.53119183],
       [ 6.72736359],
       [ 6.08564186],
       [ 4

In [30]:
y_pred2=(y_pred1>0.5)

In [31]:
y_pred2

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [32]:
y_test

array([[6],
       [5],
       [7],
       [6],
       [5],
       [6],
       [5],
       [6],
       [4],
       [5],
       [5],
       [5],
       [6],
       [5],
       [6],
       [6],
       [7],
       [5],
       [5],
       [4],
       [7],
       [6],
       [6],
       [4],
       [6],
       [5],
       [5],
       [7],
       [5],
       [6],
       [5],
       [6],
       [5],
       [6],
       [7],
       [7],
       [5],
       [6],
       [6],
       [7],
       [5],
       [7],
       [6],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [6],
       [4],
       [6],
       [5],
       [6],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [6],
    

In [33]:
x_test

array([[ 10.8  ,   0.47 ,   0.43 , ...,   3.17 ,   0.76 ,  10.8  ],
       [  8.1  ,   0.82 ,   0.   , ...,   3.36 ,   0.53 ,   9.6  ],
       [  9.1  ,   0.29 ,   0.33 , ...,   3.26 ,   0.84 ,  11.7  ],
       ..., 
       [  9.1  ,   0.34 ,   0.42 , ...,   3.18 ,   0.55 ,  11.4  ],
       [  9.1  ,   0.765,   0.04 , ...,   3.29 ,   0.54 ,   9.7  ],
       [  8.2  ,   0.32 ,   0.42 , ...,   3.27 ,   0.55 ,  12.3  ]])

In [34]:
model.predict(x_test)

array([[ 5.82748938],
       [ 5.12794781],
       [ 6.71523952],
       [ 5.46583366],
       [ 6.08452511],
       [ 4.91532755],
       [ 5.43489218],
       [ 6.17238903],
       [ 4.91706753],
       [ 4.87283707],
       [ 5.38543653],
       [ 5.51644135],
       [ 5.85878372],
       [ 5.04291391],
       [ 5.62631798],
       [ 6.39804697],
       [ 6.95915937],
       [ 5.85571146],
       [ 6.1012373 ],
       [ 5.10078573],
       [ 6.45224571],
       [ 5.28215981],
       [ 5.74686813],
       [ 6.2046442 ],
       [ 5.63309813],
       [ 4.98946381],
       [ 5.12429619],
       [ 6.59672022],
       [ 5.14955902],
       [ 6.48760509],
       [ 6.14617109],
       [ 5.89855862],
       [ 5.69151592],
       [ 5.42579746],
       [ 5.83588123],
       [ 6.36798096],
       [ 5.17228746],
       [ 5.69742107],
       [ 6.55268574],
       [ 5.93992996],
       [ 5.48255157],
       [ 6.11818933],
       [ 6.53119183],
       [ 6.72736359],
       [ 6.08564186],
       [ 4

In [35]:
y_test

array([[6],
       [5],
       [7],
       [6],
       [5],
       [6],
       [5],
       [6],
       [4],
       [5],
       [5],
       [5],
       [6],
       [5],
       [6],
       [6],
       [7],
       [5],
       [5],
       [4],
       [7],
       [6],
       [6],
       [4],
       [6],
       [5],
       [5],
       [7],
       [5],
       [6],
       [5],
       [6],
       [5],
       [6],
       [7],
       [7],
       [5],
       [6],
       [6],
       [7],
       [5],
       [7],
       [6],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [6],
       [4],
       [6],
       [5],
       [6],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [6],
    

In [36]:
y_pred3=model.predict(np.array([[7.9,0.6,0.06,1.6,0.069,15,59,0.9964,3.3,0.46,9.4]]))

In [37]:
y_pred3

array([[ 5.11116886]], dtype=float32)

In [38]:
from sklearn import model_selection
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=260)
rfc.fit(x_train,y_train)
from sklearn.metrics import accuracy_score
y_prediction=rfc.predict(x_test)
print(accuracy_score(y_test,y_prediction)*100)

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


72.5


In [39]:
model.save('diabetes.h5')

In [40]:
get_ipython().system(u'tar -zcvf diabetes.tgz diabetes.h5')

diabetes.h5


In [41]:
import watson_machine_learning_client

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [42]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [43]:
wml_credentials={
  "url": "https://eu-gb.ml.cloud.ibm.com",
  "access_key": "0g7Cd-DM9BCiNSc2KsuqNIDfoJMPi1sphhB9Oxz_zzMF",
  "username": "0120fd2b-0d4e-4324-ae44-20b5ac88f80e",
  "password": "491f67d1-a3b2-4644-a76a-a839bb1ec967",
  "instance_id": "5949ceda-afbc-4a22-a12c-2b8acdd6f779"
}

In [44]:
client = WatsonMachineLearningAPIClient( wml_credentials )

In [45]:
metadata = {
    client.repository.ModelMetaNames.NAME: "keras model",
    client.repository.ModelMetaNames.FRAMEWORK_NAME: "tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES:[{'name':'keras','version':'2.1.3'}],
    client.repository.ModelMetaNames.FRAMEWORK_VERSION: "1.5"
}

In [46]:
print(keras.__version__)

2.1.4


In [47]:
model_details = client.repository.store_model( model="diabetes.tgz", meta_props=metadata )

In [48]:
model_id = model_details["metadata"]["guid"]
model_deployment_details = client.deployments.create( artifact_uid=model_id, name="deployment" )



#######################################################################################

Synchronous deployment creation for uid: '7daf054a-354a-4ffe-adb4-822c2fa0ea37' started

#######################################################################################


INITIALIZING
DEPLOY_IN_PROGRESS
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='5e3cab3b-55be-4126-aba3-93a546a14392'
------------------------------------------------------------------------------------------------




In [49]:
model_id = model_details["metadata"]["guid"]

In [50]:
model_id

'7daf054a-354a-4ffe-adb4-822c2fa0ea37'

In [51]:
scoring_endpoint = client.deployments.get_scoring_url(model_deployment_details)

In [52]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/5949ceda-afbc-4a22-a12c-2b8acdd6f779/deployments/5e3cab3b-55be-4126-aba3-93a546a14392/online'

In [ ]:
client.deployments.list()

In [ ]:
client.deployments.delete('97873bdf-e94f-4ceb-825e-3f30483fd93d')