In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


dataset = pd.read_csv('project1.csv')

In [2]:
dataset = dataset.dropna()

In [4]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
data=[]

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


In [5]:
for i in range(0,514):
        text=dataset['text'][i]
        text = re.sub('[^a-zA-Z]', ' ', text)
        text = text.lower()
        text = text.split()
        text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
        text = ' '.join(text)
        data.append(text)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(data).toarray()

In [7]:
y = dataset.iloc[:,0].values

In [8]:
X.shape

(514, 1487)

In [9]:
y.shape

(514,)

In [10]:
from sklearn.preprocessing import LabelEncoder
lb1=LabelEncoder()

y =lb1.fit_transform(y)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [12]:
X_test.shape

(103, 1487)

In [13]:
y.shape

(514,)

In [14]:

from keras.models import Sequential
from keras.layers import Dense
model = Sequential()

Using TensorFlow backend.


In [15]:
model.add(Dense(output_dim = 1000, init = 'uniform', activation = 'relu', input_dim = 1487))

model.add(Dense(output_dim = 1000, init = 'uniform', activation = 'relu'))

model.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])




Instructions for updating:
Colocations handled automatically by placer.


C:\Users\Jayanth\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=1487, units=1000, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
C:\Users\Jayanth\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=1000, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Jayanth\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """


In [16]:
model.fit(X_train,y_train,batch_size=200,epochs=10)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
411/411 [==============================] - 1s 3ms/step - loss: 0.6905 - acc: 0.5207
Epoch 2/10
411/411 [==============================] - 0s 384us/step - loss: 0.6219 - acc: 0.6837
Epoch 3/10
411/411 [==============================] - 0s 400us/step - loss: 0.5544 - acc: 0.9246
Epoch 4/10
411/411 [==============================] - 0s 419us/step - loss: 0.4353 - acc: 0.9392
Epoch 5/10
411/411 [==============================] - 0s 404us/step - loss: 0.2889 - acc: 0.9538
Epoch 6/10
411/411 [==============================] - 0s 400us/step - loss: 0.1619 - acc: 0.9659
Epoch 7/10
411/411 [==============================] - 0s 449us/step - loss: 0.0830 - acc: 0.9854
Epoch 8/10
411/411 [==============================] - 0s 476us/step - loss: 0.0424 - acc: 0.9927
Epoch 9/10
411/411 [==============================] - 0s 479us/step - loss: 0.0197 - acc: 0.9951
Epoch 10/10
411/411 [==============================] - 0s 393us/step - loss: 0.01

In [17]:
y_pred = model.predict(X_test)


In [18]:
y_pred =y_pred>0.5

In [19]:
y_pred

array([[False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [20]:
y_test

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1])

In [21]:
r = model.predict(cv.transform(["Awesome"]))

In [22]:
r=r>0.5

In [23]:
r

array([[ True]])

In [26]:
from tkinter import *
data1 = []
top = Tk()
top.geometry("550x300+300+150")
top.resizable(width=True, height=True)

L1 = Label(top, text="Enter Text For Prediction")
L1.pack()
E1 = Entry(top, bd =5)
E1.pack()

def predict():
    print("Prediction on progress..")
    entered_input=E1.get()
    print("Entered Input",entered_input)
    print(type(entered_input))
    prediction = model.predict_classes(cv.transform([entered_input]))
    print(prediction)
    data=["Bad Review","Good Review"]
    L2 = Label(top, text="Entered Text: "+ entered_input)
    L2.pack()
    L2 = Label(top, text="Prediction: "+ data[prediction[0][0]])
    L2.pack()
    #for i in entered_input:
        #text1 = i
        #text1 = re.sub('[^a-zA-Z]', ' ', text1)
        #text1 = text1.lower()
        #text1 = text.split()
        #text1 = [ps.stem(word) for word in text1 if not word in set(stopwords.words('english'))]
        #text1 = ' '.join(text1)
        #print(text1)
        #data1.append(text1)
        
    
        
                 
    #prediction = model.predict(cv.transform(data1))
    #print(prediction)
    #L2 = Label(top, text="Prediction: "+ str(prediction))
    #L2.pack()
    
B = Button(top, text ="Predict", command =predict)
B.pack()
top.mainloop()

Prediction on progress..
Entered Input bad
<class 'str'>
[[0]]
Prediction on progress..
Entered Input awesome
<class 'str'>
[[1]]
Prediction on progress..
Entered Input awesome
<class 'str'>
[[1]]
Prediction on progress..
Entered Input modda
<class 'str'>
[[1]]
